name: test_vibe
description: "A drivethrough experience"
publish_to: 'none'

version: 1.0.33+8

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  size_config:
    path: custom_packages/size_config-2.0.3
  html: ^0.15.6
  intl: ^0.20.2
  mime: ^2.0.0
  flutter_svg: ^2.1.0
  gif: ^2.3.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  open_file: ^3.5.10
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  dio: ^5.8.0+1
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  country_picker: ^2.0.27
  dash_flags: ^0.1.1
  flutter_multi_formatter: ^2.13.7
  collection: ^1.19.1
  equatable: ^2.0.7
  sliver_tools: ^0.2.12
  flutter_carousel_widget: ^3.1.0
  smooth_page_indicator:
    path: custom_packages/smooth_page_indicator-1.2.0
  expandable: ^5.0.1
  timeago: ^3.7.1
  flutter_bloc: ^9.1.1
  fl_chart: ^1.0.0
  just_audio: ^0.10.4
  permission_handler: ^12.0.0+1
  pretty_dio_logger: ^1.4.0
  event_bus: ^2.0.1
  image_picker: ^1.1.2
  dartz: ^0.10.1
  device_info_plus: ^11.5.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.2
  flutter_native_splash: ^2.3.5
 #firebase
  firebase_core: 3.13.0
  firebase_messaging: 15.2.5
  firebase_auth: 5.5.3
  firebase_remote_config: 5.4.3
  cloud_firestore: ^5.6.7
  # social login
  google_sign_in: 6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_local_notifications: ^19.2.1
  qr_flutter: ^4.1.0
  webview_flutter: ^4.13.0
  package_info_plus: 8.3.0
  geolocator: ^14.0.2
  sms_autofill: ^2.4.1
  pinput: ^5.0.2

dependency_overrides:
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  #  dart run build_runner build --delete-conflicting-outputs
  #  dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/core/assets/gen/
  line_length: 160
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
#  colors:
#    inputs:
#      - assets/color/colors.xml

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/demo/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/sounds/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
